---
resources:
  - name: pcfapp
    type: git
    source:
      uri: https://github.com/takay2018/pcf-workshop-app
      branch: master
    check_every: 10s
  - name: deploy-to-cf
    type: cf
    source:
      api: api.sys.pcflab.jp
      username: student-5
      password: 5svkvd20e8
      organization: handson-student5
      space: development
      skip_cert_check: true
jobs:
- name: unit-test
  plan:
  - get: pcfapp
    trigger: true
  - task: mvn-test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: maven
      inputs:
      - name: pcfapp
      caches:
      - path: pcfapp/m2   
      run:
        path: bash
        args:
        - -c
        - |
          set -e
          cd pcfapp
          rm -rf ~/.m2
          ln -fs $(pwd)/m2 ~/.m2
          mvn test
- name: build-and-deploy
  plan:
  - get: pcfapp
    passed: [ unit-test ]
    trigger: true
  - task: build
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: maven
      inputs:
      - name: pcfapp
      caches:
      - path: pcfapp/m2   
      run:
        path: bash
        args:
        - -c
        - |
          set -e
          cd pcfapp
          rm -rf ~/.m2
          ln -fs $(pwd)/m2 ~/.m2
          mvn clean package
  - put: deploy-to-cf
    params: 
      manifest: pcfapp/manifest.yml
      current_app_name: pcfapp-student-5
